server:
  port: 8089
spring:
  application:
    name: graphql-trajy
  graphql:
    url: /graphql
    graphiql:
      enabled: true
  playground:
    mapping: /playground
    settings:
      editor:
        theme: dark
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:jdbc:h2://localhost:8080/h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      show_sql: true
      use_sql_comments: true
      format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE