
spring:
  application:
    name: graphql-trajy
  graphql:
    url: /graphql
    graphiql:
      enabled: true
      path: ${spring.graphql.url}
  playground:
    mapping: /playground
    endpoint: ${spring.graphql.url}
    settings:
      editor:
        theme: dark
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:jdbc:h2://localhost:8080/h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE